[workspace]
members = [
    "lazycargo_tui",
    "lazycargo_search",
]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "MIT"

[workspace.dependencies]
base64 = "0.22.1"
chrono = { version = "0.4", features = ["serde"] }
crossterm = "0.29.0"
dirs = "6.0"
ratatui = "0.30.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
walkdir = "2.5"
